/**
 * Interface Contract: {{MODULE_NAME}}
 * Generated by Forge CTO | Date: {{DATE}}
 *
 * This contract defines the public interface between modules.
 * Implementations MUST satisfy this contract.
 * Violations will be REJECTED at PR review.
 */

// === Input Types ===

// === Output Types ===

// === Function Signatures ===

// === Error Types ===
